### PR TITLE
Adding support for `isDestroyed` function

### PR DESCRIPTION
**Pull request by vitaly-t**
This can be done without reliance on the `generic-pool`, by introducing an internal flag to be set when `.end()` is called.

In this case the function can be replaced with a property, perhaps.

Anyway, this one will work just fine for the moment.

### CODE REVIEW

**Comment by brianc** [comment]
in pg-pool 2.0 you can check `pool.ending` to see if the pool is in the process of shutting down.

**Comment by vitaly-t** [comment]
Excellent! :)

**Comment by charmander** [comment]
@vitaly-t pg-pool 2.x will be used in pg 7.x.

**Comment by brianc** [comment]
@vitaly-t - also the pool is backwards compatible with `pg@5.x` and `pg@6.x` - it's only going to be installed by _default_ when installing `pg@7.x` because `pg-pool@2.x` drops support for `node<4.x` and has a few other minor backwards incompatibilities I tried to outline here: https://github.com/brianc/node-pg-pool/pull/67

I hope to be done with `pg@7.x` this weekend!

**Pull request closed without merging**
