### PR TITLE
docs: document the remove event

### PR DESCRIPTION
**Pull request by gajus**

### CODE REVIEW

**Comment by gajus** [comment]
@brianc I have glanced through the code – it looks like I've correctly described what "remove" event signals. Correct me if I am wrong.

**Comment by brianc** [comment]
Thanks @gajus  - ah yeah I have that documented here: https://node-postgres.com/api/pool#-code-pool-on-39-remove-39-client-client-gt-void-gt-void-code-

**Comment by gajus** [comment]
I see. Would it not make sense to have it in the `node-pg-pool` repository too?

> Whenever a client is closed & removed from the pool the pool will emit the remove event.

"client is closed" does not say much. I am assuming this was meant to say ~

> Whenever a client connection is closed & the client is removed from the pool the pool will emit the remove event.

**Comment by brianc** [comment]
The plan is for the documentation on node-postgres.com to be better than the readme in this repo and replace it, rather than duplicate the documentation in both places.  Longer term I'd like to use yarn workspaces and combine a bunch of the node-postgres modules into a single repo to make doing cross-project changes easier, and at that point the docs will all need to be collected into a single place, which is why I made node-postgres.com

**Comment by gajus** [comment]
Got it.

**Pull request closed without merging**
