### PR TITLE
Remove idleListener when client is in-use

### PR DESCRIPTION
**Pull request by johanneswuerbach**
When a client is in-use, the error handling should be done by the consumer and not by the pool itself as this otherwise might cause errors to be handled multiple times.

The second commit is the actual fix here.

Based on https://github.com/brianc/node-pg-pool/pull/115

### CODE REVIEW

**Comment by vitaly-t** [comment]
@brianc Just poking 👉, to get this one merged

**Comment by johanneswuerbach** [comment]
@brianc sorry for the spam, but a review would be appreciated. Currently we need to float patches to keep up-to-date :-(

**Comment by brianc** [comment]
nope! Sorry I totally dropped the ball here. I'll merge this & push a new patch version __today__.

**Comment by charmander** [comment]
This means that for correct, complete error handling, people have to add an error listener *and* (for now) remember to remove it before returning the client to the pool.

The pool really needs to start wrapping its clients…

**Comment by charmander** [comment]
(Behaving exactly like [`ZeroPool`](https://github.com/brianc/node-postgres/issues/1938#issuecomment-516904020) plus an idle error event is probably a good target. Maybe requiring an explicit error handler, even if it’s the current default `err => { throw err; }`, would be helpful for the next major version.)

**Comment by Gobie** [comment]
This PR breaks `pool.query` error handling. It removes error handler on `connect` and attaches it back in `release`. By call using `pool.query`, which emits error like ETIMEDOUT, than the error can't be caught making the `pool.query` useless.

**Comment by johanneswuerbach** [comment]
Sorry, I send a patch PR. .query should also add an error handler to the checked out client.

**Comment by johanneswuerbach** [comment]
PR https://github.com/brianc/node-pg-pool/pull/131

**Pull request merged**
