### PR TITLE
Use double-ended queue to improve performance

### PR DESCRIPTION
**Pull request by Chocobozzz**
Because `shift()` could be expensive when the pending queue is big

### CODE REVIEW

**Comment by sehrope** [comment]
-1. I don't think it's worth the added dependency and complexity.

In normal circumstances the pending queue is not going to be large and if the pool/database cannot keep up with inbound requests then it will grow indefinitely anyway. Speeding up the queue operations won't stop that as the core slow down would be from the query execution itself.

**Comment by Chocobozzz** [comment]
Good point :+1:

**Comment by charmander** [comment]
I think it’s worth it, but that `removeFromDenque` doesn’t look like it would work.

**Comment by Chocobozzz** [comment]
I can try to fix this if maintainers of the repository are interested in this PR :)

**Pull request closed without merging**
