### PR TITLE
Clone options in Pool constructor (fixes #4)

### LINKED ISSUE #4: Pool constructor doesn't work with frozen options
Pool constructor changes given `options` parameter https://github.com/brianc/node-pg-pool/blob/master/index.js#L13-L15
This doesn't work with [frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) object. Next program terminates without error:

```js
'use strict';

var Pool = require('pg').Pool;

var config = Object.freeze({
  user: 'foo',
  password: 'secret',
  database: 'my_db',
  port: 5432
});

var pool = new Pool(config);

pool.connect(function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
  console.log('done');
});
```

Also changing user input isn't good practice, because user can use `options` object later. So, I propose to clone `options`, before adding new properties to it.

### PR DESCRIPTION
**Pull request by ikokostya**

### CODE REVIEW

**Comment by brianc** [comment]
This is perfect! Thank you @ikokostya!

**Comment by chrisvariety** [comment]
Does this break `new Pool(databaseUrlGoesHere)` ?

**Comment by brianc** [comment]
@chrisvariety it doesn't break that actually because this module doesn't currently support a database url. After spending years building highly variadic functions, I've leaned more and more towards an explicit, unforgiving interface for calling a function when possible.  To that end, the `pg-pool` constructor doesn't support a string parameter and does not do database URL parsing.  If you want to use a database URL to configure the pool I suggest something like this...

```js
var Pool = require('pg-pool')
var url = require('url')

var dbUrl = process.env.DATABASE_URL

var params = url.parse(dbUrl)
var config = {
  user: params.auth.username,
  password: params.auth.password,
  host: params.auth.hostname,
  port: params.auth.port,
  database: params.auth.pathname.split('/')[0],
}

var pool = new Pool(config)
```

That way you can extend the config with application specific options, validate individual config pieces, etc.

**Comment by chrisvariety** [comment]
@brianc Thanks for the detailed response! ✨

**Comment by brianc** [comment]
Always happy to help! I should probably add an example of that to the readme 🕵

**Pull request merged**
